### PR TITLE
Test additions and maintenance

### PR DESCRIPTION
**Pull request by computerlyrik**
First: @bwssytems Thank you for your good work!

I am owner of an A1 so i implemented some basic test as a proof-of-work of this library.
The test class may be extended with other methods testing other devices. (May need to distinguish if multiple devices are found).

To enable the Test, just remove the `@Ignore` and run `mvn clean test` on the command line.
Needs a compilable project though.

Also i cleaned up the eclipse project files and fixed the `.gitignore` - whatever IDE you are using, your eclipse files will now be hidden for git.

@bwssytems I am looking forward for your next commits. Currently i am a little short in time, so working into the protocol may take me some weeks.

Keep up the good work @bwssytems and @mob41 !

### CODE REVIEW

**Comment by computerlyrik** [comment]
Btw...this is the log of the test - seems promising (i cut out the non-java code from the class)
https://gist.github.com/computerlyrik/ce7b53f93961fd4058a8d6febd7a8f65

**Comment by a1aw** [comment]
Thank you @bwssytems  for implementing those ```BLDevice``` classes, and @computerlyrik  for some project maintenance.

But first of all, the project cannot even compiled:
- [ ] ```MP1Device.java``` contains invalid code starting from Line 48
- [ ] ```A1Device.java``` contains non-Java instructions ```else:```

:confused: I saw @bwssytems you seemed to copy the code from Python to Java directly. No, please don't do that. Some code is invalid to use in Java.

About the code style, I usually use the a modified Allman bracket style like:

```java
if (condition) {
    //before this comment, 4 spaces or 1 tab are typed.
}

//or

if (condition)
{
    //before this comment, 4 spaces or 1 tab are typed.
}
```

And spaces for each operator like ```int b = 2;```

In addition to style, I have implemented a interface to package "Packets". Each device command should have its own ```CmdPacket``` implemented. Inner classes (?) are not recommended. (though I am lazy on testing... there's one in ```RM2Device.java```)

At last, thank you for helping this project to go on! If I have time, I will help to fix the problems above.

**Comment by computerlyrik** [comment]
@mob41, thanks for your feedback. I think this was just an intermediate nightly commit by @bwssytems  :)
Some nightly builds may be broken by definition 😎

**Comment by a1aw** [comment]
What are your ideas on the distributing version format?

x.x.x-SNAPSHOT?
snapshotx.x (yours in pom)
happycow (version names?)

**Comment by bwssytems** [comment]
So, I just started putting this together. It will not compile yet. A little premature for the pull request.

**Comment by a1aw** [comment]
😄 Just a reminder to this, cause I usually compile the code before pushing

**Comment by computerlyrik** [comment]
See very dirty https://github.com/computerlyrik/broadlink-java-api/tree/compileable for a compilable version.
Dirty formatting inside. Just cleaned up non-compilable code and removed a class.

This was used to run the test outputting https://gist.github.com/computerlyrik/2f64cb2eb6cb478e00695f47b9e89eed

**Comment by bwssytems** [comment]
@mob41 Since the branch is off of my fork it will not impact you at this time. I just pasted the python code in as a template to convert, just an easy way to make sure the impl will be followed properly

@computerlyrik IT would be better if the pull request went against the AddCommands Branch, then I can pull it in and push it back to @mob41 on another Pull

**Comment by computerlyrik** [comment]
Closed in Favor of https://github.com/bwssytems/broadlink-java-api/pull/2

**Pull request closed without merging**
